pipeline {
    agent any

    tools {
        maven 'M2_HOME'
        jdk 'JAVA_HOME'
    }

    environment {
        MAVEN_OPTS = '-Xmx1024m'
    }

    stages {
        stage('Clone') {
            steps {
                git url: 'https://github.com/chayma24/5DS3-G1-devopsSping.git',
                branch: 'ChaimaGharbi-5DS3-G1',
                credentialsId: 'jenkins_token_backend'
            }
        }

        stage('Build') {
            steps {
                dir('5DS3-G1-devopsSpring') {
                    sh 'mvn clean package'
                }
            }
        } 

        stage('Test') {
            steps {
                dir('5DS3-G1-devopsSpring') {
                    sh 'mvn test -Dspring.profiles.active=test'
                }
            }
        }

        stage('Archive JAR') {
            steps {
                dir('5DS3-G1-devopsSpring/target') {
                    archiveArtifacts artifacts: '*.jar', fingerprint: true
                }
            }
        }

        stage('Notify CD Pipeline') {
            steps {
                script {
                    // Trigger CD pipeline
                    build job: 'cd_backend',
                    parameters: [
                        string(name: 'JAR_FILE', value: '**/*.jar'),
                        string(name: 'ciBuildNumber', value: "${env.BUILD_NUMBER}")
                    ]
                }
            }
        }
    }

    post {
        success {
            echo 'Build successful!!'
        }
        failure {
            echo 'Build failed'
        }
    }
}

