# Stage 1: Build Angular app
FROM node:18 AS build

WORKDIR /app
RUN npm install -g @angular/cli
RUN git clone https://github.com/chayma24/5DS3-G1-devposAngular.git .
RUN npm install
RUN ng build --configuration=production

# Stage 2: Serve app with Nginx
FROM nginx:alpine as stage-1
COPY --from=build /app/dist/5DS3-G1-devopsAngular /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]

