services:
    frontend:
        image: chayma24/5ds3-g1-devopsspring:latestAngular
        container_name: frontend
        restart: always
        ports:
            - 4200:4200
        links:
            - backend
        healthcheck:
            test: curl --fail http://localhost:4200 || exit 1
            interval: 15s
            timeout: 5s
            retries: 5
            start_period: 10s
        depends_on:
            - backend

    backend:
        image: chayma24/5ds3-g1-devopsspring:37
        container_name: backend
        restart: always
        environment:
            SPRING_PROFILES_ACTIVE: docker
        ports:
            - 8082:8082
        links:
            - mysql
        depends_on:
            - mysql

    mysql:
        image: mysql:5.7
        container_name: mysql
        ports:
            - 3306:3306
        environment:
            - MYSQL_DATABASE=devops
            - MYSQL_ROOT_PASSWORD=root
        volumes:
            - ./volumes/mysql-volume:/var/lib/mysql
        restart: always
