pipeline {
    agent any

    tools {
        maven 'M2_HOME'
        jdk 'JAVA_HOME'
    }
  
    environment {
        // Allocate a a  maximum of 1024 MB (1 GB) of heap memory.
        MAVEN_OPTS = '-Xmx1024m'
    }

    stages {
        stage('Clone') {
            steps {
                git url: 'https://github.com/chayma24/5DS3-G1-devopsSping.git',
                branch: 'ChaimaGharbi-5DS3-G1',
                credentialsId: 'jenkins_token_backend'
            }
        }

        stage('Build') {
            steps {
                dir('5DS3-G1-devopsSpring') {
                    sh 'mvn clean package'
                }
            }
        }

	stage('Test') {
            steps {
                dir('5DS3-G1-devopsSpring') {
                    sh 'mvn test -Dspring.profiles.active=test'
                }
            }
        }
        
    stage('Build Docker Image') {
            steps {
                dir('5DS3-G1-devopsSpring') {
                    script {
                        sh 'docker build -t 5ds3-g1-devopsspring .'
                    }
                }
            }
      

        stage('Push Docker Image to Docker Hub') {
    steps {
        script {
            def imageName = '5ds3-g1-devopsspring'
            def dockerHubCredentialsId = 'docker_id' 
            
            withCredentials([usernamePassword(credentialsId: dockerHubCredentialsId, passwordVariable: 'ayana666#', usernameVariable: 'chayma24')]) {
                sh "echo ayana666# | docker login -u chayma24 --password-stdin"
                sh "docker push ${imageName}"
            }
        }
    }
}


    post {
        success {
            echo 'Build successful!!'
        }
        failure {
//             mail to: 'Chayma.Gharbi@esprit.tn',
//                  subject: "Jenkins Build Failed: ${env.JOB_NAME}",
//                  body: "Build ${env.BUILD_NUMBER} of job ${env.JOB_NAME} failed. Check Jenkins for details."
            echo 'Build failed'
        }
    }
}
